inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

# Spec describe blocks and gem specification blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes
